# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dKLwPMES9hVxD8LLZYYFKgap-WlnsCEd
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import torch
# from your_project_code import NameDataset, MinimalTransformer, sample_with_temperature
# 
# # 1. Load datasets
# male_dataset = NameDataset('male_names.txt')
# female_dataset = NameDataset('female_names.txt')
# 
# # 2. Load pre-trained models
# male_model = MinimalTransformer(vocab_size=male_dataset.vocab_size, embed_size=128, num_heads=8)
# male_model.load_state_dict(torch.load('male_model.pth'))
# male_model.eval()
# 
# female_model = MinimalTransformer(vocab_size=female_dataset.vocab_size, embed_size=128, num_heads=8)
# female_model.load_state_dict(torch.load('female_model.pth'))
# female_model.eval()
# 
# # 3. Streamlit UI
# st.set_page_config(page_title="Vardų Generatorius", layout="centered")
# st.title("🎉 Vardų Generatorius")
# st.write("Sukurkite unikalius vardus naudodami dirbtinio intelekto modelį!")
# 
# # 4. Gender Selection
# gender = st.radio("Pasirinkite vardų tipą:", ["Vyriški vardai", "Moteriški vardai"])
# model = male_model if gender == "Vyriški vardai" else female_model
# dataset = male_dataset if gender == "Vyriški vardai" else female_dataset
# 
# 
# # 5. Input Controls
# start_str = st.text_input(
#     "Įveskite pradžios raides (iki 5):",
#     value="A",
#     max_chars=5,
#     help="Nurodykite vardo pradžios raides (1–5 simboliai)."
# )
# if len(start_str) > 5:
#     st.error("Pradžios raidžių skaičius negali būti didesnis nei 5!")
# 
# max_length = st.slider("Maksimalus vardo ilgis:", min_value=5, max_value=20, value=10)
# temperature = st.slider("Kūrybingumo lygis (temperatūra):", min_value=0.1, max_value=2.0, value=1.0)
# top_k = st.slider("Pasirinkti iš populiariausių variantų (top-k):", min_value=1, max_value=10, value=5)
# 
# # 6. Generate Names
# if st.button("Generuoti vardus"):
#     if len(start_str) > 0:
#         st.write(f"Sugeneruoti vardai, pradedant nuo: **{start_str}**")
#         for _ in range(10):
#             name = sample_with_temperature(
#                 model, dataset, start_str=start_str, max_length=max_length, k=top_k, temperature=temperature
#             )
#             st.markdown(f"**{name}**")
#     else:
#         st.warning("Įveskite bent vieną raidę, kad sugeneruotumėte vardus.")
#